# Site settings
title: Piedewietje 
titlesub: Handmade Bags
titlesubnl: / Handgemaakte tassen
email: info@piedewietje.nl
baseurl: ""
url: "http://www.piedewietje.nl"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: none 

sass:
    sass-dir: _sass
