# Site settings
title: Piedewietje Handmade Bags
titlesub: Handgemaakte tassen
email: your-email@domain.com
baseurl: ""
url: "http://www.piedewietje.nl"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: none 
